const queries = require('./queries');

module.exports = {
  ...queries,
  FOREIGN_KEY_VIOLATION: '23503',
  UNIQUENESS_VIOLATION: '23505',
  COMMITTEE_SLOT_VIOLATION_UNMET_REQUIREMENTS: 'CSV01',
  COMMITTEE_SLOT_VIOLATION_NO_SLOTS_REMAINING: 'CSV02',
};
